<a href="https://colab.research.google.com/github/bhagirathbhard/BA775_Notebook/blob/nightly/Team1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Startup Investments in India Market
**By: Yicheng Jiang, Bhagirath Bhardwaj, Agnes Shih, Paul Seiters, and Siddharth Bookinkere**

## Outline

#### I. Project Overview, Data Source Description and Exploratory Statistics

      1. Project Overview 
      2. Data Source Description
      3. Exploratory Statistics

#### II. What year had the most amount of start ups funded? What is the overall trend of Start up funding in India? 

#### III. What type of start ups are funded the most? 

#### IV: What cities in India had the highest amount of start ups funded in India? Is there any reason that comes to attention?

#### V: What startups had the highest funded every year?

#### VIII: Conclusion

#### IX: Public Tableau Dashboard

# I. Project Overview, Data Source Description and Exploratory Statistics
      1. Project Overview 

We are an old and very traditional money manager from the USA, investing almost exclusively in the US. After the US economy had lost a lot of its growth trajectory and the FED predicted GDP growth to linger below a mere 2% annually, our clients have been running from our investment products. Where are they all going? After booking a tee time with one of our long-time clients, we heard some adolescents with smartphones talking about the start-up scene in India. There were wild tales about startups with valuations beyond $1B, called unicorns. Apparently, there was not a hint of a slowing economy over there. Is it time to go international? After multiple people confirmed the start-up hype in India, we concluded that it is time to get ourselves a snapshot of what is going on in India. Who is investing? Where are they investing? And most importantly, which companies are they investing in? As a team, we perform data cleaning, exploratory data analysis, and finally, create a visualization in Tableau. Also, we chose the Indian Startup Funding dataset collected from multiple sources because of the varied types of funding covered, the sizable number of observations, and the time coverage from 2015 until May 2022, including the Covid-19 phase.

    2. Data Source Description

1.   Indian Startup Funding & Investment Chart [2021] (Trak.in link)
2.   Indian Startups - Funding & Investors Data [2018-2021] (Kaggle link)
3.   Indian Startup Funding & Investment Chart [2021] (Trak.in link)
4.   Indian Startups - Funding Data [2022] (Kaggle link)
5.   Funding details of the startups in India (Kaggle link)

    3. Preview of the Dataset

In [1]:
#Connect to Google Big Query
from google.colab import auth
auth.authenticate_user()

In [2]:
## Perform (Table Union) PLEASE DO NOT TOUCH -- VICTOR
%%bigquery --project=ba775-team-project-a01

SELECT Funding_Year,Company_Name,Sector,Location As HeadQuarter,Investor,Stage,USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2022`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Stage,USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2021`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Stage,USD_Amount,What_is_does AS What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2020`
UNION ALL
SELECT Funding_Year,Company AS Company_Brand,Sector,HeadQuarter,Investor,Stage,Amount___ AS USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2019`
UNION ALL
SELECT Funding_Year,Company_Name AS Company_Brand,Industry as Sector,Location as HeadQuarter,Investor,Round AS Stage,USD_Amount,About_Company as What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2018`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Stage,_Amount AS USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2017`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Stage,USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2016`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Investment_Type as Stage,USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2015`
;

,Funding_Year,Company_Name,Sector,HeadQuarter,Investor,Stage,USD_Amount,What_it_does
0,2019,Nu Genes,AgriTech,Telangana,Innovation in Food and Agriculture (IFA),None,6000000,"It is a seed company engaged in production, pr..."
1,2019,Pumpkart,E-marketplace,Chandigarh,Dinesh Dua,None,Undisclosed,B2B model for appliances and electrical products
2,2019,Smart Institute,Edtech,Surat,HNI investors,None,1500000,A platform to learn online
3,2019,Kratikal,Technology,Uttar pradesh,"Gilda VC, Art Venture, Rajeev Chitrabhanu",Pre-series A,1000000,Provides cyber security solutions
4,2019,Ess Kay Fincorp,Banking,Rajasthan,"TPG, Norwest Venture Partners, Evolvence India",None,33000000,Organised Non-Banking Finance Company
...,...,...,...,...,...,...,...,...
5689,2021,Eupheus Learning,E-learning,New Delhi,Lightrock India,Series C,"10,000,000",Offer pedagogically differentiated technology ...
5690,2021,Boutique Spirit Brands,Wine & Spirits,New Delhi,"IIFL﻿, ﻿Anicut Angel Fund﻿, ﻿Kae Capital﻿, Tra...",None,"10,000,000",Boutique Spirit Brands is a leading Brand crea...
5691,2021,Paytail,Financial Services,New Delhi,Cholamandalam,Seed,"1,500,000",Paytail is revolutionizing the offline commerc...
5692,2021,GoKwik,Information Technology & Services,New Delhi,"Matrix Partners India, Jitendra Gupta, RTP Global",Pre-series A,"5,000,000",GoKwik is a platform for solving shopping expe...
5693,2021,Vahdam,Food & Beverages,New Delhi,IIFL AMC,Series D,"20,000,000",VAHDAM is among the world’s first vertically i...

In [ ]:
## Perform (Table Union)
%%bigquery --project=ba775-team-project-a01

SELECT Funding_Year,Company_Name,Sector,Location As HeadQuarter,Investor,Stage,USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2022`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Stage,USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2021`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Stage,USD_Amount,What_is_does AS What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2020`
UNION ALL
SELECT Funding_Year,Company AS Company_Brand,Sector,HeadQuarter,Investor,Stage,Amount___ AS USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2019`
UNION ALL
SELECT Funding_Year,Company_Name AS Company_Brand,Industry as Sector,Location as HeadQuarter,Investor,Round AS Stage,USD_Amount,About_Company as What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2018`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Stage,_Amount AS USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2017`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Stage,USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2016`
UNION ALL
SELECT Funding_Year,Company_Brand,Sector,HeadQuarter,Investor,Investment_Type as Stage,USD_Amount,What_it_does
FROM `ba775-team-project-a01.Indianstartups.India_Funding_2015`
;